# Generated by Django 4.1.3 on 2022-11-29 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Nome*")),
                (
                    "iam",
                    models.CharField(
                        choices=[
                            ("S", "Selecione"),
                            ("Q", "Quero ser síndico"),
                            ("M", "Síndico morador"),
                            ("P", "Síndico profissional"),
                        ],
                        max_length=1,
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email*")),
                (
                    "phone_number",
                    models.CharField(max_length=30, verbose_name="Telefone*"),
                ),
                (
                    "condo_size",
                    models.CharField(
                        choices=[
                            ("S", "Selecione"),
                            ("P", "Até 50 unidades"),
                            ("M", "de 50 até 100 unidades"),
                            ("G", "de 100 até 200 unidades"),
                        ],
                        default="S",
                        max_length=1,
                        verbose_name="Tamanho do condomínio",
                    ),
                ),
                (
                    "number_condos",
                    models.CharField(
                        choices=[
                            ("S", "Selecione"),
                            ("N", "Nenhum"),
                            ("P", "Até 1 condomínio"),
                            ("M", "2 a 3 condomínios"),
                            ("G", "4 a 6 condomínios"),
                        ],
                        default="S",
                        max_length=1,
                        verbose_name="Quantos condomínios você administra?",
                    ),
                ),
                (
                    "solution",
                    models.CharField(
                        choices=[
                            ("S", "Selecione"),
                            ("T", "TownSq Essencial"),
                            ("A", "TownSq Administração Digital"),
                        ],
                        max_length=1,
                        verbose_name="Em qual solução da TownSq você tem interesse?*",
                    ),
                ),
            ],
        ),
    ]
